libqtile: include a py.typed file
I was puzzling through a while ago why our type annotations didn't work for
manually checking configs, it turns out that our package needs to export
this file in order to have its type annotations read, so let's do that.

This lets me do stuff like:

echo "Key([1], 1)" >> config.py

and then get fancy errors from mypy about it:

~/.qtile mypy config.py
config.py:258: error: List item 0 has incompatible type "int"; expected "str"
config.py:258: error: Argument 2 to "Key" has incompatible type "int"; expected "str"

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>