wayland/core: narrow some types
We have the right types everywhere, they have mostly just been declared as
the superclasses:

    libqtile/backend/wayland/core.py:494: error: Item "Window" of "Window | Static" has no attribute "_ptr"  [union-attr]
    libqtile/backend/wayland/core.py:494: error: Item "Static" of "Window | Static" has no attribute "_ptr"  [union-attr]
    libqtile/backend/wayland/core.py:546: error: Item "Internal" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:546: error: Item "Static" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:547: error: Item "Internal" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:547: error: Item "Static" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:549: error: Item "Internal" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:549: error: Item "Static" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:550: error: Item "Internal" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:550: error: Item "Static" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:551: error: Item "Internal" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:551: error: Item "Static" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:553: error: Item "Internal" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:553: error: Item "Static" of "Window | Internal | Static" has no attribute "group"  [union-attr]
    libqtile/backend/wayland/core.py:564: error: Item "Internal" of "Window | Internal | Static" has no attribute "activate_by_config"  [union-attr]
    libqtile/backend/wayland/core.py:564: error: Item "Static" of "Window | Internal | Static" has no attribute "activate_by_config"  [union-attr]

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>