x11: use a more direct route to the xcb connection
libqtile/backend/x11/core.py:812: error: "Window" has no attribute "window"  [attr-defined]
libqtile/backend/x11/core.py:813: error: "Window" has no attribute "window"  [attr-defined]
libqtile/backend/x11/core.py:815: error: "Window" has no attribute "window"  [attr-defined]
libqtile/backend/x11/core.py:816: error: "Window" has no attribute "window"  [attr-defined]

in all of these cases, the indirection is really being used to find the
xcbq.Connection. We have a copy of that in the core, so just use that one.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>