require cairocffi >= 1.7.0
we do not actually require this, but we are getting:

    × pip subprocess to install backend dependencies did not run successfully.
    │ exit code: 1
    ╰─> [36 lines of output]
        Collecting cffi>=1.1.0
          Downloading cffi-1.16.0.tar.gz (512 kB)
             ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 512.9/512.9 kB 9.0 MB/s eta 0:00:00
          Installing build dependencies: started
          Installing build dependencies: finished with status 'done'
          Getting requirements to build wheel: started
          Getting requirements to build wheel: finished with status 'done'
          Installing backend dependencies: started
          Installing backend dependencies: finished with status 'done'
          Preparing metadata (pyproject.toml): started
          Preparing metadata (pyproject.toml): finished with status 'done'
        Collecting cairocffi>=1.6.0 (from cairocffi[xcb]>=1.6.0)
          Using cached cairocffi-1.7.0-py3-none-any.whl.metadata (3.3 kB)
        Collecting xcffib>=1.4.0 (from cairocffi[xcb]>=1.6.0)
          Using cached xcffib-1.5.0-py3-none-any.whl
        INFO: pip is looking at multiple versions of xcffib to determine which version is compatible with other requirements. This could take a while.
          Downloading xcffib-1.4.0.tar.gz (89 kB)
             ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.5/89.5 kB 15.2 MB/s eta 0:00:00
          Preparing metadata (setup.py): started
          Preparing metadata (setup.py): finished with status 'done'
        Collecting cairocffi[xcb]>=1.6.0
          Downloading cairocffi-1.6.1-py3-none-any.whl.metadata (3.3 kB)
          Downloading cairocffi-1.6.0-py3-none-any.whl.metadata (3.3 kB)
        INFO: pip is looking at multiple versions of cairocffi[xcb] to determine which version is compatible with other requirements. This could take a while.
        INFO: pip is still looking at multiple versions of xcffib to determine which version is compatible with other requirements. This could take a while.
        ERROR: Cannot install cairocffi>=1.6.0 and cairocffi[xcb]==1.7.0 because these package versions have conflicting dependencies.

        The conflict is caused by:
            The user requested cairocffi>=1.6.0
            cairocffi[xcb] 1.7.0 depends on cairocffi 1.7.0 (from https://files.pythonhosted.org/packages/4c/0d/c9b8a12971276b33143422ff6b73aa7d74cff5f7effbffbe2a1df3bd6590/cairocffi-1.7.0-py3-none-any.whl (from https://pypi.org/simple/cairocffi/) (requires-python:>=3.8))

        To fix this you could try to:
        1. loosen the range of package versions you've specified
        2. remove package versions to allow pip attempt to solve the dependency conflict

        ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

which IMO is a pip bug, cairocffi >= 1.7.0 should satisfy cairocffi[xcb] >=
1.7.0. Let's require 1.7.0 to work around it.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>