drop __getattr__ from Configurable
This method is now one of our top allocators: on each attribute lookup, it
allocates a dict, updates it with all of the previously specified defaults,
and then does a lookup in the result. This is an expensive process that
results in memory churn.

Instead of doing this at lookup time, we can do it at
defaults-initialization time, respecting the same order as before.

Dropping __getattr__ also gives us more type checking. As a result, there
are a bunch of mypy errors:

    libqtile/config.py:1322: error: "DropDown" has no attribute "x"  [attr-defined]
    libqtile/config.py:1323: error: "DropDown" has no attribute "y"  [attr-defined]
    libqtile/config.py:1324: error: "DropDown" has no attribute "width"  [attr-defined]
    libqtile/config.py:1325: error: "DropDown" has no attribute "height"  [attr-defined]
    libqtile/config.py:1326: error: "DropDown" has no attribute "opacity"  [attr-defined]
    libqtile/config.py:1327: error: "DropDown" has no attribute "on_focus_lost_hide"  [attr-defined]
    libqtile/config.py:1328: error: "DropDown" has no attribute "warp_pointer"  [attr-defined]
    libqtile/widget/battery.py:311: error: "_LinuxBattery" has no attribute "charge_controller"  [attr-defined]
    libqtile/widget/battery.py:312: error: "_LinuxBattery" has no attribute "charge_controller"  [attr-defined]
    libqtile/widget/battery.py:313: error: "_LinuxBattery" has no attribute "force_charge"  [attr-defined]
    libqtile/popup.py:49: error: "Popup" has no attribute "opacity"  [attr-defined]
    libqtile/popup.py:57: error: "Popup" has no attribute "foreground"  [attr-defined]
    libqtile/popup.py:58: error: "Popup" has no attribute "font"  [attr-defined]
    libqtile/popup.py:59: error: "Popup" has no attribute "fontsize"  [attr-defined]
    libqtile/popup.py:60: error: "Popup" has no attribute "fontshadow"  [attr-defined]
    libqtile/popup.py:61: error: "Popup" has no attribute "wrap"  [attr-defined]
    libqtile/popup.py:64: error: "Popup" has no attribute "text_alignment"  [attr-defined]
    libqtile/popup.py:66: error: "Popup" has no attribute "border_width"  [attr-defined]
    libqtile/popup.py:66: error: "Popup" has no attribute "border"  [attr-defined]
    libqtile/popup.py:67: error: "Popup" has no attribute "border"  [attr-defined]
    libqtile/popup.py:67: error: "Popup" has no attribute "border_width"  [attr-defined]
    libqtile/popup.py:95: error: "Popup" has no attribute "border_width"  [attr-defined]
    libqtile/popup.py:98: error: "Popup" has no attribute "background"  [attr-defined]
    libqtile/popup.py:102: error: "Popup" has no attribute "horizontal_padding"  [attr-defined]
    libqtile/popup.py:103: error: "Popup" has no attribute "vertical_padding"  [attr-defined]
    libqtile/popup.py:111: error: "Popup" has no attribute "border_width"  [attr-defined]
    libqtile/popup.py:111: error: "Popup" has no attribute "border"  [attr-defined]

These are all just missing attribute declarations, so declare them.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>